// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBevxmbtoPp-Rbf7Si4pRpyQxoW6q3iUUA',
    appId: '1:167305673009:web:ba18436d63cca062139810',
    messagingSenderId: '167305673009',
    projectId: 'savetime-app-503fc',
    authDomain: 'savetime-app-503fc.firebaseapp.com',
    storageBucket: 'savetime-app-503fc.appspot.com',
    measurementId: 'G-0T9873QQMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzd7CNckHiLddq_26P7sBEa6bbsmWS9s0',
    appId: '1:167305673009:android:6eb7fee21d1a4e8e139810',
    messagingSenderId: '167305673009',
    projectId: 'savetime-app-503fc',
    storageBucket: 'savetime-app-503fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDn8yb_OGCGzVwXMDhmFp-Jp-rblZG0b4',
    appId: '1:167305673009:ios:2afdfeda1fb9286f139810',
    messagingSenderId: '167305673009',
    projectId: 'savetime-app-503fc',
    storageBucket: 'savetime-app-503fc.appspot.com',
    androidClientId: '167305673009-00ant7fskkhd1ev4g8maenp7faf9347u.apps.googleusercontent.com',
    iosBundleId: 'com.example.saveTimeCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDn8yb_OGCGzVwXMDhmFp-Jp-rblZG0b4',
    appId: '1:167305673009:ios:71604e0a9998cce1139810',
    messagingSenderId: '167305673009',
    projectId: 'savetime-app-503fc',
    storageBucket: 'savetime-app-503fc.appspot.com',
    androidClientId: '167305673009-00ant7fskkhd1ev4g8maenp7faf9347u.apps.googleusercontent.com',
    iosBundleId: 'com.example.saveTimeCustomer.RunnerTests',
  );
}
